name: Build and Deploy

on:
  repository_dispatch:
    types: [update_diary]
  # 手動でも動かせるようにする
  workflow_dispatch:

permissions:
  contents: read  # 日記生成プログラムの読み取り権限
  pages: write    # Pagesへのデプロイ権限
  id-token: write # デプロイ用の認証

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Go プログラムを取得
      - name: Checkout Code (Go Program)
        uses: actions/checkout@v4

      # 2. toasa/diary の日記データを 'data' フォルダに取得
      - name: Checkout Diary Data
        uses: actions/checkout@v4
        with:
          repository: toasa/diary
          path: data # プロジェクト内の 'data' フォルダに配置
          token: ${{ secrets.PA_TOKEN }}

      # 3. Go のセットアップ
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # 適宜最新版に

      # 4. HTML生成
      - name: Generate HTML
        run: go run main.go

      # 5. 生成されたフォルダ (public) のアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      # 6. デプロイの実行
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
